//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Topping.Core.Data.fdbo
{
    public partial class userTmp
    {
        #region Primitive Properties
    
        public virtual System.Guid PKID
        {
            get;
            set;
        }
    
        public virtual string Username
        {
            get;
            set;
        }
    
        public virtual string ApplicationName
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Comment
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual string PasswordQuestion
        {
            get;
            set;
        }
    
        public virtual string PasswordAnswer
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> IsApproved
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastActivityDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastLoginDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastPasswordChangedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreationDate
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> IsOnLine
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> IsLockedOut
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastLockedOutDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FailedPasswordAttemptCount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FailedPasswordAttemptWindowStart
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FailedPasswordAnswerAttemptCount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart
        {
            get;
            set;
        }

        #endregion
    }
}
