//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TopMachineDBModel", "FK__GamesDeta__GameC__756D6ECB", "GameConfigs", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Topping.Core.Data.SQL.GameConfigs), "GamesDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Topping.Core.Data.SQL.GamesDetail), true)]

#endregion

namespace Topping.Core.Data.SQL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TopMachineDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TopMachineDBEntities object using the connection string found in the 'TopMachineDBEntities' section of the application configuration file.
        /// </summary>
        public TopMachineDBEntities() : base("name=TopMachineDBEntities", "TopMachineDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TopMachineDBEntities object.
        /// </summary>
        public TopMachineDBEntities(string connectionString) : base(connectionString, "TopMachineDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TopMachineDBEntities object.
        /// </summary>
        public TopMachineDBEntities(EntityConnection connection) : base(connection, "TopMachineDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aspnet_Users> aspnet_Users
        {
            get
            {
                if ((_aspnet_Users == null))
                {
                    _aspnet_Users = base.CreateObjectSet<aspnet_Users>("aspnet_Users");
                }
                return _aspnet_Users;
            }
        }
        private ObjectSet<aspnet_Users> _aspnet_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameConfigs> GameConfigs
        {
            get
            {
                if ((_GameConfigs == null))
                {
                    _GameConfigs = base.CreateObjectSet<GameConfigs>("GameConfigs");
                }
                return _GameConfigs;
            }
        }
        private ObjectSet<GameConfigs> _GameConfigs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameRankings> GameRankings
        {
            get
            {
                if ((_GameRankings == null))
                {
                    _GameRankings = base.CreateObjectSet<GameRankings>("GameRankings");
                }
                return _GameRankings;
            }
        }
        private ObjectSet<GameRankings> _GameRankings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Games> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Games>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Games> _Games;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GamesDetail> GamesDetail
        {
            get
            {
                if ((_GamesDetail == null))
                {
                    _GamesDetail = base.CreateObjectSet<GamesDetail>("GamesDetail");
                }
                return _GamesDetail;
            }
        }
        private ObjectSet<GamesDetail> _GamesDetail;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aspnet_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaspnet_Users(aspnet_Users aspnet_Users)
        {
            base.AddObject("aspnet_Users", aspnet_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameConfigs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameConfigs(GameConfigs gameConfigs)
        {
            base.AddObject("GameConfigs", gameConfigs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameRankings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameRankings(GameRankings gameRankings)
        {
            base.AddObject("GameRankings", gameRankings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Games games)
        {
            base.AddObject("Games", games);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GamesDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGamesDetail(GamesDetail gamesDetail)
        {
            base.AddObject("GamesDetail", gamesDetail);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TopMachineDBModel", Name="aspnet_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aspnet_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aspnet_Users object.
        /// </summary>
        /// <param name="applicationId">Initial value of the ApplicationId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="loweredUserName">Initial value of the LoweredUserName property.</param>
        /// <param name="isAnonymous">Initial value of the IsAnonymous property.</param>
        /// <param name="lastActivityDate">Initial value of the LastActivityDate property.</param>
        public static aspnet_Users Createaspnet_Users(global::System.Guid applicationId, global::System.Guid userId, global::System.String userName, global::System.String loweredUserName, global::System.Boolean isAnonymous, global::System.DateTime lastActivityDate)
        {
            aspnet_Users aspnet_Users = new aspnet_Users();
            aspnet_Users.ApplicationId = applicationId;
            aspnet_Users.UserId = userId;
            aspnet_Users.UserName = userName;
            aspnet_Users.LoweredUserName = loweredUserName;
            aspnet_Users.IsAnonymous = isAnonymous;
            aspnet_Users.LastActivityDate = lastActivityDate;
            return aspnet_Users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                OnApplicationIdChanging(value);
                ReportPropertyChanging("ApplicationId");
                _ApplicationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationId");
                OnApplicationIdChanged();
            }
        }
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoweredUserName
        {
            get
            {
                return _LoweredUserName;
            }
            set
            {
                OnLoweredUserNameChanging(value);
                ReportPropertyChanging("LoweredUserName");
                _LoweredUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoweredUserName");
                OnLoweredUserNameChanged();
            }
        }
        private global::System.String _LoweredUserName;
        partial void OnLoweredUserNameChanging(global::System.String value);
        partial void OnLoweredUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileAlias
        {
            get
            {
                return _MobileAlias;
            }
            set
            {
                OnMobileAliasChanging(value);
                ReportPropertyChanging("MobileAlias");
                _MobileAlias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileAlias");
                OnMobileAliasChanged();
            }
        }
        private global::System.String _MobileAlias;
        partial void OnMobileAliasChanging(global::System.String value);
        partial void OnMobileAliasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAnonymous
        {
            get
            {
                return _IsAnonymous;
            }
            set
            {
                OnIsAnonymousChanging(value);
                ReportPropertyChanging("IsAnonymous");
                _IsAnonymous = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAnonymous");
                OnIsAnonymousChanged();
            }
        }
        private global::System.Boolean _IsAnonymous;
        partial void OnIsAnonymousChanging(global::System.Boolean value);
        partial void OnIsAnonymousChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TopMachineDBModel", Name="GameConfigs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameConfigs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameConfigs object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static GameConfigs CreateGameConfigs(global::System.Guid id)
        {
            GameConfigs gameConfigs = new GameConfigs();
            gameConfigs.Id = id;
            return gameConfigs;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String XmlConfig
        {
            get
            {
                return _XmlConfig;
            }
            set
            {
                OnXmlConfigChanging(value);
                ReportPropertyChanging("XmlConfig");
                _XmlConfig = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("XmlConfig");
                OnXmlConfigChanged();
            }
        }
        private global::System.String _XmlConfig;
        partial void OnXmlConfigChanging(global::System.String value);
        partial void OnXmlConfigChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TopMachineDBModel", "FK__GamesDeta__GameC__756D6ECB", "GamesDetail")]
        public EntityCollection<GamesDetail> GamesDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GamesDetail>("TopMachineDBModel.FK__GamesDeta__GameC__756D6ECB", "GamesDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GamesDetail>("TopMachineDBModel.FK__GamesDeta__GameC__756D6ECB", "GamesDetail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TopMachineDBModel", Name="GameRankings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameRankings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameRankings object.
        /// </summary>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="month">Initial value of the Month property.</param>
        /// <param name="configGameId">Initial value of the ConfigGameId property.</param>
        /// <param name="playerid">Initial value of the Playerid property.</param>
        /// <param name="percentage">Initial value of the Percentage property.</param>
        /// <param name="nbParties">Initial value of the NbParties property.</param>
        /// <param name="lostTops">Initial value of the LostTops property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="totalTops">Initial value of the TotalTops property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="serie">Initial value of the Serie property.</param>
        /// <param name="playerTop">Initial value of the PlayerTop property.</param>
        /// <param name="gameTop">Initial value of the GameTop property.</param>
        /// <param name="selection">Initial value of the Selection property.</param>
        /// <param name="bestTime">Initial value of the BestTime property.</param>
        /// <param name="bestScore">Initial value of the BestScore property.</param>
        public static GameRankings CreateGameRankings(global::System.Int32 year, global::System.Int32 month, global::System.Guid configGameId, global::System.Guid playerid, global::System.Double percentage, global::System.Int32 nbParties, global::System.Double lostTops, global::System.Int32 time, global::System.Int32 totalTops, global::System.Int32 position, global::System.Int32 serie, global::System.Int32 playerTop, global::System.Int32 gameTop, global::System.Int32 selection, global::System.Int32 bestTime, global::System.Double bestScore)
        {
            GameRankings gameRankings = new GameRankings();
            gameRankings.Year = year;
            gameRankings.Month = month;
            gameRankings.ConfigGameId = configGameId;
            gameRankings.Playerid = playerid;
            gameRankings.Percentage = percentage;
            gameRankings.NbParties = nbParties;
            gameRankings.LostTops = lostTops;
            gameRankings.Time = time;
            gameRankings.TotalTops = totalTops;
            gameRankings.Position = position;
            gameRankings.Serie = serie;
            gameRankings.PlayerTop = playerTop;
            gameRankings.GameTop = gameTop;
            gameRankings.Selection = selection;
            gameRankings.BestTime = bestTime;
            gameRankings.BestScore = bestScore;
            return gameRankings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                if (_Year != value)
                {
                    OnYearChanging(value);
                    ReportPropertyChanging("Year");
                    _Year = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Year");
                    OnYearChanged();
                }
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Month
        {
            get
            {
                return _Month;
            }
            set
            {
                if (_Month != value)
                {
                    OnMonthChanging(value);
                    ReportPropertyChanging("Month");
                    _Month = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Month");
                    OnMonthChanged();
                }
            }
        }
        private global::System.Int32 _Month;
        partial void OnMonthChanging(global::System.Int32 value);
        partial void OnMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ConfigGameId
        {
            get
            {
                return _ConfigGameId;
            }
            set
            {
                if (_ConfigGameId != value)
                {
                    OnConfigGameIdChanging(value);
                    ReportPropertyChanging("ConfigGameId");
                    _ConfigGameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConfigGameId");
                    OnConfigGameIdChanged();
                }
            }
        }
        private global::System.Guid _ConfigGameId;
        partial void OnConfigGameIdChanging(global::System.Guid value);
        partial void OnConfigGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Playerid
        {
            get
            {
                return _Playerid;
            }
            set
            {
                if (_Playerid != value)
                {
                    OnPlayeridChanging(value);
                    ReportPropertyChanging("Playerid");
                    _Playerid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Playerid");
                    OnPlayeridChanged();
                }
            }
        }
        private global::System.Guid _Playerid;
        partial void OnPlayeridChanging(global::System.Guid value);
        partial void OnPlayeridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Percentage
        {
            get
            {
                return _Percentage;
            }
            set
            {
                OnPercentageChanging(value);
                ReportPropertyChanging("Percentage");
                _Percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Percentage");
                OnPercentageChanged();
            }
        }
        private global::System.Double _Percentage;
        partial void OnPercentageChanging(global::System.Double value);
        partial void OnPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NbParties
        {
            get
            {
                return _NbParties;
            }
            set
            {
                OnNbPartiesChanging(value);
                ReportPropertyChanging("NbParties");
                _NbParties = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NbParties");
                OnNbPartiesChanged();
            }
        }
        private global::System.Int32 _NbParties;
        partial void OnNbPartiesChanging(global::System.Int32 value);
        partial void OnNbPartiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double LostTops
        {
            get
            {
                return _LostTops;
            }
            set
            {
                OnLostTopsChanging(value);
                ReportPropertyChanging("LostTops");
                _LostTops = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LostTops");
                OnLostTopsChanged();
            }
        }
        private global::System.Double _LostTops;
        partial void OnLostTopsChanging(global::System.Double value);
        partial void OnLostTopsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.Int32 _Time;
        partial void OnTimeChanging(global::System.Int32 value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalTops
        {
            get
            {
                return _TotalTops;
            }
            set
            {
                OnTotalTopsChanging(value);
                ReportPropertyChanging("TotalTops");
                _TotalTops = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTops");
                OnTotalTopsChanged();
            }
        }
        private global::System.Int32 _TotalTops;
        partial void OnTotalTopsChanging(global::System.Int32 value);
        partial void OnTotalTopsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.Int32 _Position;
        partial void OnPositionChanging(global::System.Int32 value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Serie
        {
            get
            {
                return _Serie;
            }
            set
            {
                OnSerieChanging(value);
                ReportPropertyChanging("Serie");
                _Serie = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Serie");
                OnSerieChanged();
            }
        }
        private global::System.Int32 _Serie;
        partial void OnSerieChanging(global::System.Int32 value);
        partial void OnSerieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerTop
        {
            get
            {
                return _PlayerTop;
            }
            set
            {
                OnPlayerTopChanging(value);
                ReportPropertyChanging("PlayerTop");
                _PlayerTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayerTop");
                OnPlayerTopChanged();
            }
        }
        private global::System.Int32 _PlayerTop;
        partial void OnPlayerTopChanging(global::System.Int32 value);
        partial void OnPlayerTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameTop
        {
            get
            {
                return _GameTop;
            }
            set
            {
                OnGameTopChanging(value);
                ReportPropertyChanging("GameTop");
                _GameTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameTop");
                OnGameTopChanged();
            }
        }
        private global::System.Int32 _GameTop;
        partial void OnGameTopChanging(global::System.Int32 value);
        partial void OnGameTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Selection
        {
            get
            {
                return _Selection;
            }
            set
            {
                OnSelectionChanging(value);
                ReportPropertyChanging("Selection");
                _Selection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selection");
                OnSelectionChanged();
            }
        }
        private global::System.Int32 _Selection;
        partial void OnSelectionChanging(global::System.Int32 value);
        partial void OnSelectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BestTime
        {
            get
            {
                return _BestTime;
            }
            set
            {
                OnBestTimeChanging(value);
                ReportPropertyChanging("BestTime");
                _BestTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BestTime");
                OnBestTimeChanged();
            }
        }
        private global::System.Int32 _BestTime;
        partial void OnBestTimeChanging(global::System.Int32 value);
        partial void OnBestTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double BestScore
        {
            get
            {
                return _BestScore;
            }
            set
            {
                OnBestScoreChanging(value);
                ReportPropertyChanging("BestScore");
                _BestScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BestScore");
                OnBestScoreChanged();
            }
        }
        private global::System.Double _BestScore;
        partial void OnBestScoreChanging(global::System.Double value);
        partial void OnBestScoreChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TopMachineDBModel", Name="Games")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Games : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Games object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="gameConfigId">Initial value of the GameConfigId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="gameXml">Initial value of the GameXml property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Games CreateGames(global::System.Guid gameId, global::System.Guid gameConfigId, global::System.DateTime date, global::System.Int32 status, global::System.String gameXml, global::System.String name)
        {
            Games games = new Games();
            games.GameId = gameId;
            games.GameConfigId = gameConfigId;
            games.Date = date;
            games.Status = status;
            games.GameXml = gameXml;
            games.Name = name;
            return games;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Guid _GameId;
        partial void OnGameIdChanging(global::System.Guid value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GameConfigId
        {
            get
            {
                return _GameConfigId;
            }
            set
            {
                OnGameConfigIdChanging(value);
                ReportPropertyChanging("GameConfigId");
                _GameConfigId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameConfigId");
                OnGameConfigIdChanged();
            }
        }
        private global::System.Guid _GameConfigId;
        partial void OnGameConfigIdChanging(global::System.Guid value);
        partial void OnGameConfigIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GameXml
        {
            get
            {
                return _GameXml;
            }
            set
            {
                OnGameXmlChanging(value);
                ReportPropertyChanging("GameXml");
                _GameXml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GameXml");
                OnGameXmlChanged();
            }
        }
        private global::System.String _GameXml;
        partial void OnGameXmlChanging(global::System.String value);
        partial void OnGameXmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TopMachineDBModel", Name="GamesDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GamesDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GamesDetail object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static GamesDetail CreateGamesDetail(global::System.Guid gameId, global::System.DateTime date)
        {
            GamesDetail gamesDetail = new GamesDetail();
            gamesDetail.GameId = gameId;
            gamesDetail.Date = date;
            return gamesDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Guid _GameId;
        partial void OnGameIdChanging(global::System.Guid value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Guid> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DetailXml
        {
            get
            {
                return _DetailXml;
            }
            set
            {
                OnDetailXmlChanging(value);
                ReportPropertyChanging("DetailXml");
                _DetailXml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DetailXml");
                OnDetailXmlChanged();
            }
        }
        private global::System.String _DetailXml;
        partial void OnDetailXmlChanging(global::System.String value);
        partial void OnDetailXmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Solos
        {
            get
            {
                return _Solos;
            }
            set
            {
                OnSolosChanging(value);
                ReportPropertyChanging("Solos");
                _Solos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Solos");
                OnSolosChanged();
            }
        }
        private Nullable<global::System.Int32> _Solos;
        partial void OnSolosChanging(Nullable<global::System.Int32> value);
        partial void OnSolosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Warnings
        {
            get
            {
                return _Warnings;
            }
            set
            {
                OnWarningsChanging(value);
                ReportPropertyChanging("Warnings");
                _Warnings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warnings");
                OnWarningsChanged();
            }
        }
        private Nullable<global::System.Int32> _Warnings;
        partial void OnWarningsChanging(Nullable<global::System.Int32> value);
        partial void OnWarningsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _Time;
        partial void OnTimeChanging(Nullable<global::System.Int32> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Percentage
        {
            get
            {
                return _Percentage;
            }
            set
            {
                OnPercentageChanging(value);
                ReportPropertyChanging("Percentage");
                _Percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Percentage");
                OnPercentageChanged();
            }
        }
        private Nullable<global::System.Double> _Percentage;
        partial void OnPercentageChanging(Nullable<global::System.Double> value);
        partial void OnPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TopLost
        {
            get
            {
                return _TopLost;
            }
            set
            {
                OnTopLostChanging(value);
                ReportPropertyChanging("TopLost");
                _TopLost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TopLost");
                OnTopLostChanged();
            }
        }
        private Nullable<global::System.Int32> _TopLost;
        partial void OnTopLostChanging(Nullable<global::System.Int32> value);
        partial void OnTopLostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Top
        {
            get
            {
                return _Top;
            }
            set
            {
                OnTopChanging(value);
                ReportPropertyChanging("Top");
                _Top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Top");
                OnTopChanged();
            }
        }
        private Nullable<global::System.Int32> _Top;
        partial void OnTopChanging(Nullable<global::System.Int32> value);
        partial void OnTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Negative
        {
            get
            {
                return _Negative;
            }
            set
            {
                OnNegativeChanging(value);
                ReportPropertyChanging("Negative");
                _Negative = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Negative");
                OnNegativeChanged();
            }
        }
        private Nullable<global::System.Int32> _Negative;
        partial void OnNegativeChanging(Nullable<global::System.Int32> value);
        partial void OnNegativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Selection
        {
            get
            {
                return _Selection;
            }
            set
            {
                OnSelectionChanging(value);
                ReportPropertyChanging("Selection");
                _Selection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selection");
                OnSelectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Selection;
        partial void OnSelectionChanging(Nullable<global::System.Int32> value);
        partial void OnSelectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private Nullable<global::System.Int32> _Rating;
        partial void OnRatingChanging(Nullable<global::System.Int32> value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> GameConfigId
        {
            get
            {
                return _GameConfigId;
            }
            set
            {
                OnGameConfigIdChanging(value);
                ReportPropertyChanging("GameConfigId");
                _GameConfigId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameConfigId");
                OnGameConfigIdChanged();
            }
        }
        private Nullable<global::System.Guid> _GameConfigId;
        partial void OnGameConfigIdChanging(Nullable<global::System.Guid> value);
        partial void OnGameConfigIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TopMachineDBModel", "FK__GamesDeta__GameC__756D6ECB", "GameConfigs")]
        public GameConfigs GameConfigs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameConfigs>("TopMachineDBModel.FK__GamesDeta__GameC__756D6ECB", "GameConfigs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameConfigs>("TopMachineDBModel.FK__GamesDeta__GameC__756D6ECB", "GameConfigs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GameConfigs> GameConfigsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GameConfigs>("TopMachineDBModel.FK__GamesDeta__GameC__756D6ECB", "GameConfigs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GameConfigs>("TopMachineDBModel.FK__GamesDeta__GameC__756D6ECB", "GameConfigs", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
